using System.Threading.Tasks;
using AirSnitch.Core.Domain.Models;

namespace AirSnitch.TelegramBot.Commands.Start
{
    /// <summary>
    /// Interface that represent command generated by user and recived by client.
    /// </summary>
    public interface IExecutableTelegramCommand<TArgs> : ITelegramCommand
    {
        /// <summary>
        /// Asynchronously execute command
        /// </summary>
        /// <returns></returns>
        Task ExecuteAsync(TArgs commandArgs);
    }

    public interface ITelegramCommand
    {
        public string Tag { get; }
    }
}
