FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /App

# Copy csproj and restore as distinct layers
COPY ["AirSnitch.API/AirSnitch.API.csproj", "AirSnitch.API/"]
COPY ["AirSnitch.Di/AirSnitch.Di.csproj", "AirSnitch.Di/"]
COPY ["AirSnitch.Domain/AirSnitch.Domain.csproj", "AirSnitch.Domain/"]
COPY ["AirSnitch.Infrastructure/AirSnitch.Infrastructure.csproj", "AirSnitch.Infrastructure/"]
COPY ["AirSnitch.Infrastructure.Abstract/AirSnitch.Infrastructure.Abstract.csproj", "AirSnitch.Infrastructure.Abstract/"]
COPY ["AirSnitch.Worker/AirSnitch.Worker.csproj", "AirSnitch.Worker/"]

# Copy everything
COPY . ./
WORKDIR "/App/AirSnitch.Worker"
# Restore as distinct layers
RUN dotnet restore
# Build and publish a release
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/runtime:6.0
WORKDIR /App
COPY --from=build-env /App/AirSnitch.Worker/out .
ENTRYPOINT ["dotnet", "AirSnitch.Worker.dll"]
