name: Deploy API

on:
   workflow_dispatch:
   push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'api_*.*.*'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: |
            cd src
            flyctl secrets set --app airsnitch-api MongoDbSettings__ConnectionString=${{ secrets.MONGO_CONNECTIONSTRING_EU_CUSTER }} 
            flyctl secrets set --app airsnitch-api MongoDbSettings__DbName=${{ secrets.MONGO_DBNAME_EU_CUSTER }}
            flyctl deploy --config fly-api.toml --remote-only
