name: Deploy API

on:
   workflow_dispatch:
   push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'api_*.*.*'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy-api:
      name: Deploy api
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: |
            cd src
            flyctl deploy --config fly-api.toml --remote-only
  deploy-worker:
      name: Deploy worker
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: |
            cd src
            flyctl deploy --remote-only
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: 0.9.0
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes
