name: Deploy worker

on:
   push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: |
            cd src
            flyctl deploy --remote-only -e MongoDbSettings__ConnectionString=${{ secrets.MONGO_CONNECTIONSTRING_EU_CUSTER }} MongoDbSettings__DbName=${{ secrets.MONGO_DBNAME_EU_CUSTER }} AmazonSqsSettings__ServiceUrl=${{ secrets.AMZ_SQS_SERVICE_URL }} AmazonSqsSettings__QueueUrl=${{ secrets.AMZ_SQS_QUEUE_URL }} AmazonSqsSettings__AccessKey=${{ secrets.AMZ_SQS_ACCESS_KEY }} AmazonSqsSettings__AccessSecrete=${{ secrets.AMZ_SQS_ACCESS_SECRETE }} 
