name: Deploy worker

on:
   workflow_dispatch:
   push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'worker_*.*.*'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: |
            cd src
            flyctl deploy --remote-only
